package jogodavelha;

public class Jogo extends javax.swing.JFrame {

public boolean joga=true;
public boolean jogb=true;
public int contpos=0;
public int k=0, i=0;
int hh;
public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal1, diagonal2;
String[][]posvetor=new String[3][3];
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txttela = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btnreset.setText("REINICIAR");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        txttela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txttela.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttela, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(btnreset))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(txttela, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnreset)
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void verifJogador(){
        if(joga&&jogb){
        this.hh=1;
        joga=false;
        jogb=true;
        txttela.setText("Vez do Jogador O");
    }else if(joga&&jogb==false){
        this.hh=1;
        joga=false;
        jogb=true;
        txttela.setText("Vez do Jogador O");
    }else{
        this.hh=2;
        joga=true;
        jogb=false;
        txttela.setText("Vez do Jogador X");
        }
    }
    
     public void limpa(){
for(i=0;i<3;i++){
    for(k=0;k<3;k++){
        posvetor[i][k]="";
        System.out.println(posvetor[i][k]);
    }
} 
}
     public void FinalizaJogo(){
         btn1.setEnabled(false);
         btn2.setEnabled(false);
         btn3.setEnabled(false);
         btn4.setEnabled(false);
         btn5.setEnabled(false);
         btn6.setEnabled(false);
         btn7.setEnabled(false);
         btn8.setEnabled(false);
         btn9.setEnabled(false);
     }
     public void verifica(){
    contpos=0;
             for(i=0;i<3;i++){
    for(k=0;k<3;k++){
        if("X".equals(posvetor[i][k])|"O".equals(posvetor[i][k])){
            contpos+=1;
        }
                        
        }
    }
     }
    public void VerifWinner(){
    linha1=posvetor[0][0]+posvetor[0][1]+posvetor[0][2];
    linha2=posvetor[1][0]+posvetor[1][1]+posvetor[1][2];
    linha3=posvetor[2][0]+posvetor[2][1]+posvetor[2][2];
    
    coluna1=posvetor[0][0]+posvetor[1][0]+posvetor[2][0];
    coluna2=posvetor[0][1]+posvetor[1][1]+posvetor[2][1];
    coluna3=posvetor[0][2]+posvetor[1][2]+posvetor[2][2];
    
    diagonal1=posvetor[0][0]+posvetor[1][1]+posvetor[2][2];
    diagonal2=posvetor[0][2]+posvetor[1][1]+posvetor[2][0];
    
    if(linha1.equals("XXX")|linha2.equals("XXX")|linha3.equals("XXX")|coluna1.equals("XXX")|coluna2.equals("XXX")|coluna3.equals("XXX")|diagonal1.equals("XXX")|diagonal2.equals("XXX")){
        txttela.setText("Parabéns X é o vencendor!!!");
        FinalizaJogo();
    }else if(linha1.equals("OOO")|linha2.equals("OOO")|linha3.equals("OOO")|coluna1.equals("OOO")|coluna2.equals("OOO")|coluna3.equals("OOO")|diagonal1.equals("OOO")|diagonal2.equals("OOO")){
        txttela.setText("Parabéns O é o vencendor!!!");
        FinalizaJogo();
    
    }else if(contpos==9){
        txttela.setText("DEU VELHA!!!");
    }
    }
    
   
    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       verifJogador();
    if(hh==1){
    btn5.setText("X");
    posvetor[1][1]="X";
    }else{
     btn5.setText("O");
    posvetor[1][1]="O";
    }
    btn5.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       verifJogador();
    if(hh==1){
    btn8.setText("X");
    posvetor[2][1]="X";
    }else{
     btn8.setText("O");
    posvetor[2][1]="O";
    }  
    btn8.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
    verifJogador();
    if(hh==1){
    btn1.setText("X");
    posvetor[0][0]="X";
    }else{
     btn1.setText("O");
    posvetor[0][0]="O";
    }
    btn1.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        verifJogador();
    if(hh==1){
    btn2.setText("X");
    posvetor[0][1]="X";
    }else{
     btn2.setText("O");
    posvetor[0][1]="O";
    }
    btn2.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        verifJogador();
    if(hh==1){
    btn3.setText("X");
    posvetor[0][2]="X";
    }else{
     btn3.setText("O");
    posvetor[0][2]="O";
    }
    btn3.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
       verifJogador();
    if(hh==1){
    btn4.setText("X");
    posvetor[1][0]="X";
    }else{
     btn4.setText("O");
    posvetor[1][0]="O";
    }
    btn4.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        verifJogador();
    if(hh==1){
    btn6.setText("X");
    posvetor[1][2]="X";
    }else{
     btn6.setText("O");
    posvetor[1][2]="O";
    }
    btn6.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        verifJogador();
    if(hh==1){
    btn7.setText("X");
    posvetor[2][0]="X";
    }else{
     btn7.setText("O");
    posvetor[2][0]="O";
    }
    btn7.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        verifJogador();
    if(hh==1){
    btn9.setText("X");
    posvetor[2][2]="X";
    }else{
     btn9.setText("O");
    posvetor[2][2]="O";
    }
    btn9.setEnabled(false);
    verifica();
    VerifWinner();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
btn1.setText("");
btn1.setEnabled(true);

btn2.setText("");
btn2.setEnabled(true);

btn3.setText("");
btn3.setEnabled(true);

btn4.setText("");
btn4.setEnabled(true);

btn5.setText("");
btn5.setEnabled(true);

btn6.setText("");
btn6.setEnabled(true);

btn7.setText("");
btn7.setEnabled(true);

btn8.setText("");
btn8.setEnabled(true);

btn9.setText("");
btn9.setEnabled(true);
limpa();
txttela.setText("");
joga=true;
jogb=true;
 
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnreset;
    private javax.swing.JTextField txttela;
    // End of variables declaration//GEN-END:variables
}
